version: '3.9'

services:

  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: testDb
    ports:
      - 5432:5432